# Generated by Django 6.0.2 on 2026-03-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_systemsetting_userprofile_is_approved_auditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmid', models.IntegerField(help_text='Moodle Course Module ID', unique=True)),
                ('prerequisite_cmid', models.IntegerField(blank=True, help_text='Must complete this module first', null=True)),
                ('disable_seeking', models.BooleanField(default=False)),
                ('disable_fast_forward', models.BooleanField(default=False)),
                ('min_watch_percent', models.IntegerField(blank=True, null=True)),
                ('quiz_time_limit', models.IntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('auto_submit', models.BooleanField(default=False)),
                ('max_attempts', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
