# Generated by Django 6.0.2 on 2026-03-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_modulerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='moodle_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
