# Generated by Django 6.0.2 on 2026-03-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_userprofile_moodle_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='Moodle User ID')),
                ('course_id', models.IntegerField()),
                ('cmid', models.IntegerField(help_text='Moodle Course Module ID')),
                ('watched_seconds', models.IntegerField()),
                ('total_duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
