# Generated by Django 6.0.2 on 2026-03-20 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_watchlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('signature_image', models.ImageField(upload_to='cert_signatures/')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cert_signer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course_id', models.IntegerField(blank=True, help_text='Moodle Course ID this template is for', null=True)),
                ('background_image', models.ImageField(upload_to='cert_templates/')),
                ('font_family', models.CharField(default='Poppins', max_length=100)),
                ('student_name_x', models.IntegerField(default=500)),
                ('student_name_y', models.IntegerField(default=300)),
                ('course_name_x', models.IntegerField(default=500)),
                ('course_name_y', models.IntegerField(default=380)),
                ('signature_x', models.IntegerField(default=800)),
                ('signature_y', models.IntegerField(default=500)),
                ('qr_x', models.IntegerField(default=900)),
                ('qr_y', models.IntegerField(default=520)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('verification_code', models.CharField(max_length=64, unique=True)),
                ('certificate_file', models.CharField(blank=True, help_text='Relative path to generated PNG in media/', max_length=500)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.certificatetemplate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['teacher', 'course_id'], name='frontend_ce_teacher_6307e1_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedcertificate',
            index=models.Index(fields=['verification_code'], name='frontend_is_verific_a11b75_idx'),
        ),
    ]
