# Generated by Django 6.0.2 on 2026-03-20 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(default='Success', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
