# Generated by Django 6.0.2 on 2026-03-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cmid', models.IntegerField(help_text='Moodle Course Module ID', unique=True)),
                ('module_type', models.CharField(help_text='e.g., video, quiz, url', max_length=50)),
                ('mpd_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
