# Generated by Django 6.0.2 on 2026-03-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='cmid',
            new_name='moodle_cmid',
        ),
        migrations.RenameField(
            model_name='modulerule',
            old_name='cmid',
            new_name='moodle_cmid',
        ),
        migrations.RenameField(
            model_name='watchlog',
            old_name='cmid',
            new_name='moodle_cmid',
        ),
    ]
