# Generated by Codex on 2026-03-26
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_module_moodle_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='moodle_cmid',
            field=models.IntegerField(help_text='Moodle Course Module ID', unique=True),
        ),
    ]
