# Generated by Django 6.0.2 on 2026-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_module_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='moodle_cmid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
