# Generated by Codex on 2026-03-26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_studentmoduleprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='moodle_course_id',
            field=models.IntegerField(blank=True, help_text='Moodle Course ID this module belongs to', null=True),
        ),
    ]
