# Generated by Django 6.0.2 on 2026-03-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_module_moodle_cmid'),
        ('frontend', '0015_studentmoduleprogress'),
    ]

    operations = [
    ]
