# Generated by Django 6.0.2 on 2026-03-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_merge_20260326_1236'),
        ('frontend', '0016_module_moodle_course_id'),
    ]

    operations = [
    ]
