# Generated by Codex on 2026-03-26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_module_moodle_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmoduleprogress',
            name='last_position_seconds',
            field=models.FloatField(default=0),
        ),
    ]
