# Generated by Django 6.0.2 on 2026-03-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_merge_20260326_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmoduleprogress',
            name='last_position_seconds',
            field=models.FloatField(default=0),
        ),
    ]
