# Generated by Django 6.0.2 on 2026-03-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_studentmoduleprogress_last_position'),
        ('frontend', '0018_studentmoduleprogress_last_position_seconds'),
    ]

    operations = [
    ]
