# Generated by Django 6.0.2 on 2026-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_merge_20260326_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmoduleprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmoduleprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
