# Generated by Django 6.0.2 on 2026-03-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_studentmoduleprogress_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmoduleprogress',
            name='completed',
        ),
    ]
