# Generated by Django 6.0.2 on 2026-03-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_course_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
